services:
  nestjs_starter_test_postgres: # Edit
    image: postgres:alpine
    container_name: nestjs_starter_test_postgres # Edit
    restart: no
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - nestjs_starter_test_postgres_data:/var/lib/postgresql/data # Edit
  
  nestjs_starter_test_redis:
    image: redis:alpine
    container_name: nestjs_starter_test_redis # Edit
    ports:
      - '6381:6379'
    volumes:
      - nestjs_starter_test_redis_data:/data # Edit

networks:
  default:
    name: nestjs_starter_test # Edit

volumes:
  nestjs_starter_test_postgres_data: # Edit
  nestjs_starter_test_redis_data: # Edit
