services:
  nestjs_starter_prod_app: # Edit
    build: .
    container_name: nestjs_starter_prod_app # Edit
    restart: always
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:6100:6100"
    depends_on:
      - nestjs_starter_prod_postgres
      - nestjs_starter_prod_redis

  nestjs_starter_prod_postgres: # Edit
    image: postgres:alpine
    container_name: nestjs_starter_prod_postgres # Edit
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nestjs_starter_prod_postgres_data:/var/lib/postgresql/data # Edit
  
  nestjs_starter_prod_redis:
    image: redis:alpine
    container_name: nestjs_starter_prod_redis # Edit
    volumes:
      - nestjs_starter_prod_redis_data:/data # Edit

networks:
  default:
    name: nestjs_starter_prod # Edit

volumes:
  nestjs_starter_prod_postgres_data: # Edit
  nestjs_starter_prod_redis_data: # Edit
