services:
  nest_starter_app: # Edit
    image: shirokuronemuri/nest-starter:latest
    container_name: nest_starter_app # Edit
    restart: always
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:6100:6100"
    depends_on:
      - nest_starter_postgres
      - nest_starter_redis

  nest_starter_postgres: # Edit
    image: postgres:alpine
    container_name: nest_starter_postgres # Edit
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nest_starter_postgres_data:/var/lib/postgresql/data # Edit
  
  nest_starter_redis:
    image: redis:alpine
    container_name: nest_starter_redis # Edit
    restart: always
    volumes:
      - nest_starter_redis_data:/data # Edit

networks:
  default:
    name: nest_starter_prod # Edit

volumes:
  nest_starter_postgres_data: # Edit
  nest_starter_redis_data: # Edit
